#define LINE_WIDTH 200

#define ART_ROW 1
#define ART_COL 1

#define LOG_ROW 32
#define LOG_COL 1

#define INPUT_ROW LOG_ROW + 1
#define INPUT_COL 1

#define SENSOR_TABLE_ROW_BEGIN SWITCH_TABLE_ROW_BEGIN
#define SENSOR_TABLE_COL 30

#define SUBSCRIBE_TABLE_ROW_BEGIN SWITCH_TABLE_ROW_BEGIN + 10
#define SUBSCRIBE_TABLE_COL SENSOR_TABLE_COL

#define PATH_ROW_BEGIN SUBSCRIBE_TABLE_ROW_BEGIN + 10
#define PATH_COL SENSOR_TABLE_COL

#define IDLE_ROW 5
#define IDLE_COL 1

#define TIME_ROW 6
#define TIME_COL 1

#define SWITCH_TABLE_ROW_BEGIN 8
#define SWITCH_TABLE_COL 1
#define SWITCH_TABLE_WIDTH 20

#define DEBUG_TABLE_ROW_BEGIN INPUT_ROW + 2
#define DEBUG_TABLE_COL 1